var categories = [
	[{random: ""}, 
	 {random: ""}, 
	 {random: ""}, 
	 {random: ""}, 
	 {random: ""}, 
	 {random: ""}], 
	
	[{dog: ""},
	 {dog: ""},
	 {dog: ""}, 
	 {cat: ""},
	 {cat: ""}, 
	 {cat: ""},  
	 {chick: ""},
	 {chick: ""},
	 {chick: ""} 
	 {sheep: ""},
	 {sheep: ""},
	 {sheep: ""}, 
	 {duckling: ""},
	 {duckling: ""},
	 {duckling: ""}, 
	 {dolphin: ""},
	 {dolphin: ""},
	 {dolphin: ""}, 
	 {rabbit: ""},
	 {rabbit: ""},
	 {rabbit: ""}, 
	 {panda: ""},
	 {panda: ""},
	 {panda: ""}], 
	
	[{purple: ""}, 
	 {blue: ""}, 
	 {green: ""}, 
	 {pink: ""}]
];