var categories = [
	[{random: ""}, 
	 {random: ""}, 
	 {random: ""}, 
	 {random: ""}, 
	 {random: ""}, 
	 {random: ""}], 
	
	[{dog: ""},
	 {dog: ""},
	 {dog: ""}, 
	 {cat: ""},
	 {cat: ""}, 
	 {cat: ""},  
	 {chick: ""},
	 {chick: ""},
	 {chick: ""} 
	 {sheep: ""},
	 {sheep: ""},
	 {sheep: ""}, 
	 {duckling: ""},
	 {duckling: ""},
	 {duckling: ""}, 
	 {dolphin: ""},
	 {dolphin: ""},
	 {dolphin: ""}, 
	 {rabbit: ""},
	 {rabbit: ""},
	 {rabbit: ""}, 
	 {panda: ""},
	 {panda: ""},
	 {panda: ""}], 
	//colors
	[{blue: "#20B2AA"},
	 {light_blue: "#B0E0E6"}, 
	 {light_purple: "#EE82EE"},
	 {purple: "#BA55D3"}, 
	 {light_green: "#90EE90"}, 
	 {green: "#32CD32"},
	 {light_pink: "#FFC0CB"},
	 {light_yellow: "#F0E68C"},
	 {orange: "#FFA500"},
	 {light_orange: "#FAA460"}]
];