var categories = [
	[{random: ""}, 
	 {random: ""}, 
	 {random: ""}, 
	 {random: ""}, 
	 {random: ""}, 
	 {random: ""}], 
	
	[{dog: "http://www.dogbreedidentifier.com/wp-content/uploads/2014/09/corgi-puppy.jpg"},
	 {dog: "http://www.dogbreedidentifier.com/wp-content/uploads/2014/09/spitz-puppy.png"},
	 {dog: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRVST0ZfFU9-2Mmuvt6RZnxGyZs3Rr1GW3HIQgMrLUoWgYVgZU9Cw"}, 
	 {dog: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRKWkKnWYGfIpE_zi3WELpUmDMG7g8utorrr7p-n0AATLva8OBcIQ"},
	 {dog: "http://cdn.cutestpaw.com/wp-content/uploads/2011/11/Seemly-l.jpg"},
	 {dog: "http://cdn.cutestpaw.com/wp-content/uploads/2011/11/Puppy-scrunch-faces-l.jpg"}, 
	 {cat: "https://lh6.ggpht.com/PCrc5I3dFmhyQENQZfvcHjmSgomMnrueKDZ12T1rFk0yNuAXzbgUr9TxNS95Tm65csSL=h900"},
	 {cat: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtHGd54bbHGSI91H5LeTamfXy6cOh3YHpuuX9tcN6dcpTKA7uV"}, 
	 {cat: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQduHdZjIsJokf3ZwCtl7WBwC8mBORDX6gC6fRpUY2LHrXU6A12"},  
	 {chick: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRx9pvN15wLX5O8nh0E9VHw7UR0YcVjserv9ce_t54P8LHp9tpCHQ"},
	 {chick: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQhkVn1v1-ylZyEZLffaCWRnY6hbtao6f8HU9ts1P-Tos5QYCPY"},
	 {chick: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQq09QAZU0HMg4qvZ8ktocPk2BgwleFk5qpkDMD8lOLMioViAk0"},
	 {sheep: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTD7NXGTd7KzISM-sEzN-O3P9zLFQpYNLMM6YQ0J3h_Or6Oudbg"},
	 {sheep: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTt8Ac4hEwfDvkS9szC5aUqTeWQJqpZRrbcwWAfkaEQX8WYKbTy"},
	 {sheep: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcROZaBpNl09B_dtTfYlZz1DBJd6Wd4SgljXcDoPhRF05zhski40qA"}, 
	 {duckling: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWw-NnD_Lkz6hoAdhEpl0F6XG9nLeF6XPiPfyzcpe54cZE2jsg"},
	 {duckling: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQnsUr9h9gohAgMbeMTc1baY4lPadj50Wy5eVT9zSXmxMewfx2FsA"},
	 {duckling: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRddhX9A5nHM3dG8kcRrH40aSQMP4gZ1Y-kYie8S8o68wFUYZJJ"}, 
	 {dolphin: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0HGsVuppHtwSwgjlRtxAzUPnGg2js1Ig642pyd0ZbAFpPSdk3"},
	 {dolphin: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSbieVPAXC_X_62MdLMNIbFzFg2D1ORI4peaC8Z5pqdcbeRcRxn"},
	 {dolphin: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQnsUr9h9gohAgMbeMTc1baY4lPadj50Wy5eVT9zSXmxMewfx2FsA"}, 
	 {rabbit: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRtEEoz597SWqNBlNUKQW4pcz3ttdyFwmv5E2x6oGgDkQpk8x2ujA"},
	 {rabbit: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQMoEQtT1qFbM6220lMfI31rPBGaBewZzvkfpnV_ny2dDE0KPOU"},
	 {rabbit: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTLE3kELcERE7WKn_F4VtJBPQ7ASCMYfeuUwMgTyaAyBbGvtDA2"}, 
	 {panda: "http://teacher.scholastic.com/commclub/babypanda_activity1/assets/images/photo_cvr_babypanda_hr.jpg"},
	 {panda: "http://media3.s-nbcnews.com/j/streams/2013/August/130813/6C8613205-tdy-130813-baby-panda-07.blocks_desktop_medium.jpg"},
	 {panda: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGSONbUUKOZXvj-BuukE_7ODqKjYhZ0ha4e9VLVcqDLcohj0Sh"}], 
	
	[{purple: ""}, 
	 {blue: ""}, 
	 {green: ""}, 
	 {pink: ""}]
];